# 应用服务 WEB 访问端口
server:
  port: 58080

spring:
  # 配置两个数据源
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/mybatis_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456

    postgresql:
      url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: postgres
      password: 123456

#指定Mybatis的Mapper文件
mybatis:
#  mapper-locations: classpath:mappers/*xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


