# 应用服务 WEB 访问端口
server:
  port: 58080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


